// =========================
// 📜 QUESTS & NIVELES (1 - 60)
// =========================

const QUESTS = [
    // ⚔️ ZONA 1: EL CEMENTERIO DEL SELECT (Niveles 1-5)
    { n: "El Guardián de la Puerta", hp: 100, boss: false, t: "Muestra todos los guerreros disponibles en el abismo.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Esqueleto Indagador", hp: 120, boss: false, t: "Selecciona solo los nombres de los guerreros. Ignora el resto.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT nombre FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Acólito del Orden", hp: 130, boss: false, t: "Muestra la clase y el nivel de todos los guerreros.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT clase, nivel FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Espectro de la Cantidad", hp: 150, boss: false, t: "Muestra solo los primeros 3 guerreros usando LIMIT.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros LIMIT 3", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "El Inquisidor del Orden", hp: 300, boss: true, t: "Muestra todos los guerreros ordenados por su nivel, del más fuerte al más débil.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros ORDER BY nivel DESC", req: { hasWhere: false, hasJoin: false, hasGroup: false } },

    // 🛡️ ZONA 2: LAS CATACUMBAS DEL FILTRADO (Niveles 6-15)
    { n: "Centinela de Élite", hp: 150, boss: false, t: "Encuentra el nombre y nivel de los guerreros que superen el nivel 10.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT nombre, nivel FROM guerreros WHERE nivel > 10", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Mago Hereje", hp: 180, boss: false, t: "Encuentra al guerrero llamado 'Radahn'. Muestra todos sus datos.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros WHERE nombre = 'Radahn'", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Espíritu Dual", hp: 200, boss: false, t: "Busca guerreros que tengan nivel mayor a 10 Y menor a 60.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros WHERE nivel > 10 AND nivel < 60", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Aparición Errática", hp: 200, boss: false, t: "Encuentra a los guerreros llamados 'Malenia' o 'Godrick'.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros WHERE nombre = 'Malenia' OR nombre = 'Godrick'", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Sombra del Vacío", hp: 220, boss: false, t: "Muestra los guerreros cuya clase sea 'Mago' o 'Clérigo' usando IN.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros WHERE clase IN ('Mago', 'Clérigo')", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Gólem de la Negación", hp: 220, boss: false, t: "Muestra todos los guerreros EXCEPTO los que son de clase 'Guerrero'.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros WHERE clase != 'Guerrero'", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Bestia del Rango", hp: 240, boss: false, t: "Muestra los guerreros cuyo HP esté entre 500 y 1000 usando BETWEEN.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros WHERE hp BETWEEN 500 AND 1000", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Demonio de la Riqueza", hp: 250, boss: false, t: "Muestra los nombres de los guerreros que tienen más de 5000 almas.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT nombre FROM guerreros WHERE almas > 5000", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Cazador Ciego", hp: 250, boss: false, t: "Muestra los guerreros que NO tienen 0 almas.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT * FROM guerreros WHERE almas > 0", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Caballero del Crisol", hp: 450, boss: true, t: "Muestra el nombre y las almas del top 2 guerreros con más almas que superen el nivel 10.", s: "Tabla: guerreros (id, nombre, nivel, clase, hp, almas)", expected: "SELECT nombre, almas FROM guerreros WHERE nivel > 10 ORDER BY almas DESC LIMIT 2", req: { hasWhere: true, hasJoin: false, hasGroup: false } },

    // 🔗 ZONA 3: EL PUENTE DE LOS VÍNCULOS (Niveles 16-25)
    { n: "Acólito de la Unión", hp: 250, boss: false, t: "Muestra el nombre del guerrero y el nombre de su arma usando JOIN.", s: "Tablas: guerreros(id, nombre) | armas(nombre, guerrero_id)", expected: "SELECT guerreros.nombre, armas.nombre FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id", req: { hasWhere: false, hasJoin: true, hasGroup: false } },
    { n: "Herrero Corrupto", hp: 260, boss: false, t: "Muestra el nombre del guerrero y el nombre del arma, solo para armas de daño mayor a 100.", s: "Tablas: guerreros(id, nombre) | armas(nombre, guerrero_id, danio)", expected: "SELECT guerreros.nombre, armas.nombre FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id WHERE armas.danio > 100", req: { hasWhere: true, hasJoin: true, hasGroup: false } },
    { n: "Vigilante del Vínculo", hp: 280, boss: false, t: "Encuentra qué guerrero porta la 'Mano de Malenia'. Muestra el nombre del guerrero.", s: "Tablas: guerreros(id, nombre) | armas(nombre, guerrero_id)", expected: "SELECT guerreros.nombre FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id WHERE armas.nombre = 'Mano de Malenia'", req: { hasWhere: true, hasJoin: true, hasGroup: false } },
    { n: "Caballero Sin Armas", hp: 300, boss: false, t: "Muestra TODOS los guerreros y sus armas usando LEFT JOIN, incluso si no tienen arma.", s: "Tablas: guerreros(id, nombre) | armas(nombre, guerrero_id)", expected: "SELECT guerreros.nombre, armas.nombre FROM guerreros LEFT JOIN armas ON guerreros.id = armas.guerrero_id", req: { hasWhere: false, hasJoin: true, hasGroup: false } },
    { n: "El Olvidado", hp: 320, boss: false, t: "Usando LEFT JOIN, encuentra al guerrero que NO tiene ningún arma asignada (donde el id del arma es nulo).", s: "Tablas: guerreros(id, nombre) | armas(id, nombre, guerrero_id)", expected: "SELECT guerreros.nombre FROM guerreros LEFT JOIN armas ON guerreros.id = armas.guerrero_id WHERE armas.id IS NULL", req: { hasWhere: true, hasJoin: true, hasGroup: false } },
    { n: "Nigromante de Magias", hp: 330, boss: false, t: "Une guerreros con sus hechizos. Muestra el nombre del guerrero y el nombre del hechizo.", s: "Tablas: guerreros(id, nombre) | hechizos(nombre, guerrero_id)", expected: "SELECT guerreros.nombre, hechizos.nombre FROM guerreros JOIN hechizos ON guerreros.id = hechizos.guerrero_id", req: { hasWhere: false, hasJoin: true, hasGroup: false } },
    { n: "Erudito Arcano", hp: 340, boss: false, t: "Muestra a los guerreros y sus hechizos, pero solo aquellos cuyo hechizo cueste menos de 50 SP.", s: "Tablas: guerreros(id, nombre) | hechizos(nombre, costo_sp, guerrero_id)", expected: "SELECT guerreros.nombre, hechizos.nombre FROM guerreros JOIN hechizos ON guerreros.id = hechizos.guerrero_id WHERE hechizos.costo_sp < 50", req: { hasWhere: true, hasJoin: true, hasGroup: false } },
    { n: "Maestro del Doble Filo", hp: 350, boss: false, t: "Une a los guerreros con sus armas y ordénalos por el daño del arma de mayor a menor.", s: "Tablas: guerreros(id, nombre) | armas(nombre, danio, guerrero_id)", expected: "SELECT guerreros.nombre, armas.nombre, armas.danio FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id ORDER BY armas.danio DESC", req: { hasWhere: false, hasJoin: true, hasGroup: false } },
    { n: "Sombra Gemela", hp: 360, boss: false, t: "Muestra los guerreros de clase 'Mago' junto con las armas que portan.", s: "Tablas: guerreros(id, nombre, clase) | armas(nombre, guerrero_id)", expected: "SELECT guerreros.nombre, armas.nombre FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id WHERE guerreros.clase = 'Mago'", req: { hasWhere: true, hasJoin: true, hasGroup: false } },
    { n: "Margarit, la Bestia del JOIN", hp: 600, boss: true, t: "Triple unión: Muestra el nombre del guerrero, su arma y su hechizo. (Usa JOIN dos veces).", s: "Tablas: guerreros(id, nombre) | armas(nombre, guerrero_id) | hechizos(nombre, guerrero_id)", expected: "SELECT guerreros.nombre, armas.nombre, hechizos.nombre FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id JOIN hechizos ON guerreros.id = hechizos.guerrero_id", req: { hasWhere: false, hasJoin: true, hasGroup: false } },

    // 🧮 ZONA 4: EL PANTANO DE LA AGRUPACIÓN (Niveles 26-35)
    { n: "Contador de Almas", hp: 350, boss: false, t: "Cuenta el número total de guerreros vivos usando COUNT(*).", s: "Tabla: guerreros (id, nombre)", expected: "SELECT COUNT(*) FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Tasador de Poder", hp: 360, boss: false, t: "Calcula el nivel promedio de todos los guerreros usando AVG(nivel).", s: "Tabla: guerreros (nivel)", expected: "SELECT AVG(nivel) FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Herrero Titánico", hp: 370, boss: false, t: "Encuentra el arma con el mayor daño usando MAX(danio).", s: "Tabla: armas (danio)", expected: "SELECT MAX(danio) FROM armas", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Cobarde Oculto", hp: 380, boss: false, t: "Encuentra el menor HP entre todos los guerreros usando MIN(hp).", s: "Tabla: guerreros (hp)", expected: "SELECT MIN(hp) FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Banquero del Abismo", hp: 390, boss: false, t: "Suma todas las almas de todos los guerreros usando SUM(almas).", s: "Tabla: guerreros (almas)", expected: "SELECT SUM(almas) FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Maestro de las Facciones", hp: 400, boss: false, t: "Cuenta cuántos guerreros hay por cada clase usando GROUP BY.", s: "Tabla: guerreros (clase)", expected: "SELECT clase, COUNT(*) FROM guerreros GROUP BY clase", req: { hasWhere: false, hasJoin: false, hasGroup: true } },
    { n: "Estratega de Combate", hp: 420, boss: false, t: "Muestra el HP máximo por cada clase de guerrero.", s: "Tabla: guerreros (clase, hp)", expected: "SELECT clase, MAX(hp) FROM guerreros GROUP BY clase", req: { hasWhere: false, hasJoin: false, hasGroup: true } },
    { n: "Organizador de Armerías", hp: 440, boss: false, t: "Agrupa las armas por 'tipo' y muestra el daño promedio de cada tipo.", s: "Tabla: armas (tipo, danio)", expected: "SELECT tipo, AVG(danio) FROM armas GROUP BY tipo", req: { hasWhere: false, hasJoin: false, hasGroup: true } },
    { n: "Tribunal Exigente", hp: 460, boss: false, t: "Muestra las clases que tengan más de 1 guerrero usando HAVING.", s: "Tabla: guerreros (clase)", expected: "SELECT clase, COUNT(*) FROM guerreros GROUP BY clase HAVING COUNT(*) > 1", req: { hasWhere: false, hasJoin: false, hasGroup: true } },
    { n: "Renala, Reina de la Agrupación", hp: 750, boss: true, t: "Une guerreros con sus armas. Muestra el nombre del guerrero y SUMA el daño total de todas las armas que porta (agrupando por nombre).", s: "Tablas: guerreros(id, nombre) | armas(danio, guerrero_id)", expected: "SELECT guerreros.nombre, SUM(armas.danio) FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id GROUP BY guerreros.nombre", req: { hasWhere: false, hasJoin: true, hasGroup: true } },

    // 🔍 ZONA 5: LA CIUDAD DE LAS CADENAS Y EL VACÍO (Niveles 36-45)
    { n: "Lector de Runas", hp: 400, boss: false, t: "Encuentra a los guerreros cuyo nombre empiece con la letra 'M' usando LIKE 'M%'.", s: "Tabla: guerreros (nombre)", expected: "SELECT * FROM guerreros WHERE nombre LIKE 'M%'", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Buscador de Ecos", hp: 410, boss: false, t: "Encuentra las armas cuyo nombre termine con la letra 'a'.", s: "Tabla: armas (nombre)", expected: "SELECT * FROM armas WHERE nombre LIKE '%a'", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Verdugo del Medio", hp: 420, boss: false, t: "Muestra guerreros cuyo nombre contenga la palabra 'Rey' en cualquier parte.", s: "Tabla: guerreros (nombre)", expected: "SELECT * FROM guerreros WHERE nombre LIKE '%Rey%'", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Gritón de la Cima", hp: 430, boss: false, t: "Muestra los nombres de los guerreros convertidos a MAYÚSCULAS (Usa UPPER).", s: "Tabla: guerreros (nombre)", expected: "SELECT UPPER(nombre) FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Susurrador del Valle", hp: 440, boss: false, t: "Muestra las clases en minúsculas usando LOWER.", s: "Tabla: guerreros (clase)", expected: "SELECT LOWER(clase) FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Juez de Longitud", hp: 450, boss: false, t: "Selecciona los nombres de los guerreros cuyo nombre tenga exactamente 7 letras (Usa LENGTH).", s: "Tabla: guerreros (nombre)", expected: "SELECT nombre FROM guerreros WHERE LENGTH(nombre) = 7", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Cazador Preciso", hp: 460, boss: false, t: "Busca a los guerreros que tengan una 'a' como la segunda letra de su nombre (LIKE '_a%').", s: "Tabla: guerreros (nombre)", expected: "SELECT * FROM guerreros WHERE nombre LIKE '_a%'", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Fantasma del Vacío", hp: 470, boss: false, t: "Encuentra a los guerreros cuyo nombre NO contenga la letra 'e'.", s: "Tabla: guerreros (nombre)", expected: "SELECT * FROM guerreros WHERE nombre NOT LIKE '%e%'", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Mendigo Nulo", hp: 480, boss: false, t: "Encuentra los guerreros que NO tienen una clase asignada (Usa IS NULL).", s: "Tabla: guerreros (nombre, clase)", expected: "SELECT * FROM guerreros WHERE clase IS NULL", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Rykard, Señor de la Blasfemia", hp: 850, boss: true, t: "Muestra las armas que pertenezcan a un guerrero cuyo nombre empiece con 'G' (Usa JOIN y LIKE).", s: "Tablas: armas(nombre, guerrero_id) | guerreros(id, nombre)", expected: "SELECT armas.nombre FROM armas JOIN guerreros ON armas.guerrero_id = guerreros.id WHERE guerreros.nombre LIKE 'G%'", req: { hasWhere: true, hasJoin: true, hasGroup: false } },

    // 🌀 ZONA 6: EL ABISMO DE LAS SUBCONSULTAS (Niveles 46-55)
    { n: "Espejismo Menor", hp: 500, boss: false, t: "Encuentra el nombre del guerrero que tiene el nivel más alto usando una subconsulta.", s: "Tabla: guerreros (nombre, nivel)", expected: "SELECT nombre FROM guerreros WHERE nivel = (SELECT MAX(nivel) FROM guerreros)", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Guardián del Promedio", hp: 520, boss: false, t: "Muestra los guerreros que tienen un nivel mayor al nivel promedio.", s: "Tabla: guerreros (nombre, nivel)", expected: "SELECT * FROM guerreros WHERE nivel > (SELECT AVG(nivel) FROM guerreros)", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Ladrón de Arsenal", hp: 540, boss: false, t: "Usando IN y una subconsulta, encuentra los guerreros que poseen un arma de tipo 'Espada'.", s: "Tablas: guerreros(id, nombre) | armas(guerrero_id, tipo)", expected: "SELECT nombre FROM guerreros WHERE id IN (SELECT guerrero_id FROM armas WHERE tipo = 'Espada')", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Monje Pacifista", hp: 560, boss: false, t: "Usando NOT IN y una subconsulta, encuentra a los guerreros que NO tienen ningún arma.", s: "Tablas: guerreros(id, nombre) | armas(guerrero_id)", expected: "SELECT nombre FROM guerreros WHERE id NOT IN (SELECT guerrero_id FROM armas)", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Vidente de la Pobreza", hp: 580, boss: false, t: "Encuentra a los guerreros cuyas almas sean menores al promedio de almas de todos los de clase 'Mago'.", s: "Tabla: guerreros (nombre, almas, clase)", expected: "SELECT nombre FROM guerreros WHERE almas < (SELECT AVG(almas) FROM guerreros WHERE clase = 'Mago')", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Duplicador de Daño", hp: 600, boss: false, t: "Muestra el nombre del arma y calcula el doble de su daño (danio * 2) en los resultados.", s: "Tabla: armas (nombre, danio)", expected: "SELECT nombre, danio * 2 FROM armas", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Matemático Loco", hp: 620, boss: false, t: "Muestra el nombre de los guerreros y su HP restante si sufrieran 50 puntos de daño (hp - 50).", s: "Tabla: guerreros (nombre, hp)", expected: "SELECT nombre, hp - 50 FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Observador Constante", hp: 640, boss: false, t: "Usa EXISTS para mostrar todos los guerreros, solo SI existe algún arma con más de 500 de daño.", s: "Tablas: guerreros(*) | armas(danio)", expected: "SELECT * FROM guerreros WHERE EXISTS (SELECT 1 FROM armas WHERE danio > 500)", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Ilusionista del Vacío", hp: 660, boss: false, t: "Usa COALESCE para mostrar la clase del guerrero. Si la clase es NULL, muestra 'Desconocido'.", s: "Tabla: guerreros (nombre, clase)", expected: "SELECT nombre, COALESCE(clase, 'Desconocido') FROM guerreros", req: { hasWhere: false, hasJoin: false, hasGroup: false } },
    { n: "Malekith, la Hoja de Subconsultas", hp: 1000, boss: true, t: "Encuentra el nombre del guerrero que porta el arma con el MAYOR daño de toda la base de datos (Usa JOIN y una subconsulta con MAX).", s: "Tablas: guerreros(nombre, id) | armas(guerrero_id, danio)", expected: "SELECT guerreros.nombre FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id WHERE armas.danio = (SELECT MAX(danio) FROM armas)", req: { hasWhere: true, hasJoin: true, hasGroup: false } },

    // 👑 ZONA 7: EL TRONO DEL ELDEN LORD (Niveles 56-60)
    { n: "Guardia del Rey Supremo", hp: 800, boss: false, t: "Triple JOIN: Muestra el nombre del guerrero, su arma y su hechizo, pero SOLO de aquellos con nivel mayor a 50.", s: "Tablas: guerreros, armas, hechizos", expected: "SELECT guerreros.nombre, armas.nombre, hechizos.nombre FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id JOIN hechizos ON guerreros.id = hechizos.guerrero_id WHERE guerreros.nivel > 50", req: { hasWhere: true, hasJoin: true, hasGroup: false } },
    { n: "Archimago del Tiempo", hp: 850, boss: false, t: "Muestra la clase de los guerreros y la SUMA de sus almas, pero solo muestra las clases cuya suma de almas supere 10000. Ordena de mayor a menor.", s: "Tabla: guerreros(clase, almas)", expected: "SELECT clase, SUM(almas) FROM guerreros GROUP BY clase HAVING SUM(almas) > 10000 ORDER BY SUM(almas) DESC", req: { hasWhere: false, hasJoin: false, hasGroup: true } },
    { n: "Campeón de la Dualidad", hp: 900, boss: false, t: "Muestra el nombre de las armas cuyo daño supere el daño PROMEDIO de TODAS las armas.", s: "Tabla: armas(nombre, danio)", expected: "SELECT nombre FROM armas WHERE danio > (SELECT AVG(danio) FROM armas)", req: { hasWhere: true, hasJoin: false, hasGroup: false } },
    { n: "Dios Externo", hp: 1200, boss: true, t: "Cuenta cuántas armas tiene cada guerrero. Muestra el nombre del guerrero y su cantidad de armas (Usa JOIN y GROUP BY).", s: "Tablas: guerreros(id, nombre) | armas(guerrero_id)", expected: "SELECT guerreros.nombre, COUNT(armas.id) FROM guerreros LEFT JOIN armas ON guerreros.id = armas.guerrero_id GROUP BY guerreros.nombre", req: { hasWhere: false, hasJoin: true, hasGroup: true } },
    { n: "Radagon de la Orden Dorada (FINAL BOSS)", hp: 2000, boss: true, t: "LA PRUEBA FINAL: Únete a ti mismo. Encuentra el nombre del guerrero y el daño de su arma. Agrúpalos por el nombre del guerrero, suma su daño total, filtra solo los que tengan un daño total superior a 100, ordénalos de mayor a menor daño, y muestra solo al TOP 1.", s: "El dominio absoluto de SQL.", expected: "SELECT guerreros.nombre, SUM(armas.danio) FROM guerreros JOIN armas ON guerreros.id = armas.guerrero_id GROUP BY guerreros.nombre HAVING SUM(armas.danio) > 100 ORDER BY SUM(armas.danio) DESC LIMIT 1", req: { hasWhere: false, hasJoin: true, hasGroup: true } }
];